laravel/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/admin/posts');
});

Route::middleware('guest:admin')->group(function(){
	Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
	Route::post('login_process', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
});

Route::middleware('auth:admin')->group(function(){
	Route::resource('posts', App\Http\Controllers\Admin\PostController::class);
	Route::get('logout', [App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');

	Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
});

laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//	return view('welcome');
//});

//Auth::routes();


Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
Route::get('/posts', [App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
Route::get('/posts/{id}', [App\Http\Controllers\PostController::class, 'show'])->name('posts.show');

Route::get('/contacts', [App\Http\Controllers\IndexController::class, 'showContactForme'])->name('contacts');
Route::post('/contact_form_process', [App\Http\Controllers\IndexController::class, 'contactForm'])->name('contact_form_process');

//мидлвар для авторзованных
Route::middleware("auth")->group(function () {
	Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
	Route::post('/posts/comment/{id}', [App\Http\Controllers\PostController::class, 'comment'])->name('comment');
});

//мидлвар для неавторизованных
Route::middleware("guest")->group(function () {
	Route::get('/login', [App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
	Route::post('/login_process', [App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

	Route::get('/register', [App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
	Route::post('/register_process', [App\Http\Controllers\AuthController::class, 'register'])->name('register_process');
	
	Route::get('/forgot', [App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
	Route::post('/forgot_process', [App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

laravel/resources/views/layout/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@yield('title')</title>
	<link href="/css/app.css" rel="stylesheet">
		{{-- Tailwindcss --}}
		<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
		<script src="https://cdn.tailwindcss.com"></script>
		<style type="text/tailwindcss">
			@layer utilities {
			  .content-auto {
				 content-visibility: auto;
			  }
			}
		 </style>
		 {{-- endTailwindcss --}}
</head>
<body>
	<div>
		<div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
			 <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>

			 <div :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'" class="fixed z-30 inset-y-0 left-0 w-64 transition duration-300 transform bg-gray-900 overflow-y-auto lg:translate-x-0 lg:static lg:inset-0">
				  <div class="flex items-center justify-center mt-8">
						<div class="flex items-center">
							 <svg class="h-12 w-12" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
								  <path d="M364.61 390.213C304.625 450.196 207.37 450.196 147.386 390.213C117.394 360.22 102.398 320.911 102.398 281.6C102.398 242.291 117.394 202.981 147.386 172.989C147.386 230.4 153.6 281.6 230.4 307.2C230.4 256 256 102.4 294.4 76.7999C320 128 334.618 142.997 364.608 172.989C394.601 202.981 409.597 242.291 409.597 281.6C409.597 320.911 394.601 360.22 364.61 390.213Z" fill="#4C51BF" stroke="#4C51BF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
								  <path d="M201.694 387.105C231.686 417.098 280.312 417.098 310.305 387.105C325.301 372.109 332.8 352.456 332.8 332.8C332.8 313.144 325.301 293.491 310.305 278.495C295.309 263.498 288 256 275.2 230.4C256 243.2 243.201 320 243.201 345.6C201.694 345.6 179.2 332.8 179.2 332.8C179.2 352.456 186.698 372.109 201.694 387.105Z" fill="white"></path>
							 </svg>
						</div>
				  </div>

				  <nav class="mt-10">
					<a href="{{ route('admin.admin_users.index') }}"
						class="text-gray-100 flex items-center mt-4 py-2 px-6">

						 <span class="mx-3">Пользователи</span>
					</a>

					<a href="{{ route('admin.posts.index') }}"
						class="text-gray-100 flex items-center mt-4 py-2 px-6">

						 <span class="mx-3">Статьи</span>
					</a>
			  </nav>
			 </div>

			 <div class="flex-1 flex flex-col overflow-hidden">
				  <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-indigo-600">
						<div class="flex items-center">
							 <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
								  <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
												stroke-linejoin="round"></path>
								  </svg>
							 </button>
						</div>

						<div class="flex items-center">
							 <div x-data="{ dropdownOpen: false }" class="relative">
								  <button @click="dropdownOpen = ! dropdownOpen"
											 class="relative block h-8 w-8 rounded-full overflow-hidden shadow focus:outline-none">
										<img class="h-full w-full object-cover"
											  src="https://images.unsplash.com/photo-1528892952291-009c663ce843?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=296&amp;q=80"
											  alt="Your avatar">
								  </button>

								  <div x-show="dropdownOpen" @click="dropdownOpen = false" class="fixed inset-0 h-full w-full z-10"
										 style="display: none;"></div>

								  <div x-show="dropdownOpen"
										 class="absolute right-0 mt-2 w-48 bg-white rounded-md overflow-hidden shadow-xl z-10"
										 style="display: none;">
										<a href="{{ route('admin.logout') }}"
											class="block px-4 py-2 text-sm text-gray-700 hover:bg-indigo-600 hover:text-white">Выйти</a>
								  </div>
							 </div>
						</div>
				  </header> 
				  
				  <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
						@yield('content')
				  </main>
			 </div>
		</div>
  </div>
	
	<script src="/js/app.js"></script>
</body>
</html>

laravel/resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@yield('title')</title>
	<link href="/css/app.css" rel="stylesheet">
	{{-- Tailwindcss --}}
	<script src="https://cdn.tailwindcss.com"></script>
	<style type="text/tailwindcss">
		@layer utilities {
		  .content-auto {
			 content-visibility: auto;
		  }
		}
	 </style>
	 {{-- endTailwindcss --}}
</head>
</head>
<body>
	@yield('content')
	
	<script src="/js/app.js"></script>
</body>
</html>