laravel/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/admin/posts');
});

Route::middleware('guest:admin')->group(function(){
	Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
	Route::post('login_process', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
});

Route::middleware('auth:admin')->group(function(){
	Route::resource('posts', App\Http\Controllers\Admin\PostController::class);
	Route::get('logout', [App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');

	Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
});

laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//	return view('welcome');
//});

//Auth::routes();


Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
Route::get('/posts', [App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
Route::get('/posts/{id}', [App\Http\Controllers\PostController::class, 'show'])->name('posts.show');

Route::get('/contacts', [App\Http\Controllers\IndexController::class, 'showContactForme'])->name('contacts');
Route::post('/contact_form_process', [App\Http\Controllers\IndexController::class, 'contactForm'])->name('contact_form_process');

//мидлвар для авторзованных
Route::middleware("auth")->group(function () {
	Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
	Route::post('/posts/comment/{id}', [App\Http\Controllers\PostController::class, 'comment'])->name('comment');
});

//мидлвар для неавторизованных
Route::middleware("guest")->group(function () {
	Route::get('/login', [App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
	Route::post('/login_process', [App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

	Route::get('/register', [App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
	Route::post('/register_process', [App\Http\Controllers\AuthController::class, 'register'])->name('register_process');
	
	Route::get('/forgot', [App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
	Route::post('/forgot_process', [App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

laravel/app/Models/AdminUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AdminUser extends Authenticatable
{
	use HasFactory;

	protected $fillable = [
		'name',
		'email',
		'password',
	];

	public function roles(){
		return $this->belongsToMany(Role::class);
	}
}

laravel/app/Http/Controllers/Admin/AdminUserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AdminUserFormRequest;
use App\Models\AdminUser;

class AdminUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = AdminUser::orderBy("created_at", "DESC")->paginate(3);

        return view("admin.admin_users.index", [
            "users" => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.admin_users.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  AdminUserFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminUserFormRequest $request)
    {
        $data = $request->validated();

        $user = AdminUser::create($data);

		  $user->roles()->sync($data["roles"] ?? []);

        return redirect(route("admin.admin_users.index"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = AdminUser::findOrFail($id);

        return view("admin.admin_users.create", [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  AdminUserFormRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUserFormRequest $request, $id)
    {
        $user = AdminUser::findOrFail($id);

        $user->update($request->validated());

        return redirect(route("admin.admin_users.index"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        AdminUser::destroy($id);

        return redirect(route("admin.admin_users.index"));
    }
}

laravel/resources/views/admin/admin_users/create.blade.php
@extends('layout.admin')

@section('title',  isset($user) ? "Редактировать пользователя ID {$user->id}" : 'Добавить пользователя')

@section('content')
    <div class="container mx-auto px-6 py-8">
        <h3 class="text-gray-700 text-3xl font-medium">{{ isset($user) ? "Редактировать пользователя ID {$user->id}" : 'Добавить пользователя' }}</h3>

        <div class="mt-8">

        </div>

        <div class="mt-8">
            <form enctype="multipart/form-data" class="space-y-5 mt-5" method="POST" action="{{ isset($user) ? route("admin.admin_users.update", $user->id) : route("admin.admin_users.store") }}">
                @csrf

                @if(isset($user))
                    <input type="hidden" name="id" value="{{ $user->id }}"/>

                    @method('PUT')
                @endif

                <input name="email" type="text" class="w-full h-12 border border-gray-800 rounded px-3 @error('email') border-red-500 @enderror" placeholder="E-mail" value="{{ $user->email ?? '' }}" />

                @error('email')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                <input name="name" type="text" class="w-full h-12 border border-gray-800 rounded px-3 @error('name') border-red-500 @enderror" placeholder="Имя" value="{{ $user->name ?? '' }}" />

                @error('name')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                <input name="password" type="password" autocomplete="new-password" class="w-full h-12 border border-gray-800 rounded px-3 @error('password') border-red-500 @enderror" placeholder="Пароль" value="" />
                <input name="password_confirmation" type="password" autocomplete="new-password"  class="w-full h-12 border border-gray-800 rounded px-3 @error('password') border-red-500 @enderror" placeholder="Подтверждение пароля" value="" />

                @error('password')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

laravel/resources/views/admin/admin_users/index.blade.php
@extends('layout.admin')

@section('title', 'Администраторы')

@section('content')
    <div class="container mx-auto px-6 py-8">
        <h3 class="text-gray-700 text-3xl font-medium">Администраторы</h3>

        <div class="mt-8">
            <a href="{{ route("admin.admin_users.create") }}" class="text-indigo-600 hover:text-indigo-900">Добавить</a>
        </div>

        <div class="flex flex-col mt-8">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                <div
                        class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
                    <table class="min-w-full">
                        <thead>
                        <tr>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                E-mail</th>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50"></th>
                        </tr>
                        </thead>

                        <tbody class="bg-white">
                            @foreach($users as $user)
                                <tr>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                        <div class="text-sm leading-5 text-gray-900">{{ $user->email }}</div>
                                    </td>

                                    <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium">
													@can('update', $post)
														<a href="{{ route("admin.admin_users.edit", $user->id) }}" class="text-indigo-600 hover:text-indigo-900">Редактировать</a>
													@endcan
													@can('delete', $post) 
                                        <form action="{{ route("admin.admin_users.destroy", $user->id) }}" method="POST">
                                            @csrf

                                            @method('DELETE')

                                            <button type="submit" class="text-red-600 hover:text-red-900">Удалить</button>
                                        </form>
													 @endcan

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection