laravel/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/admin/posts');
});

Route::middleware('guest:admin')->group(function(){
	Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
	Route::post('login_process', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
});

Route::middleware('auth:admin')->group(function(){
	Route::resource('posts', App\Http\Controllers\Admin\PostController::class);
	Route::get('logout', [App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');

	Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
});

laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//	return view('welcome');
//});

//Auth::routes();


Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
Route::get('/posts', [App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
Route::get('/posts/{id}', [App\Http\Controllers\PostController::class, 'show'])->name('posts.show');

Route::get('/contacts', [App\Http\Controllers\IndexController::class, 'showContactForme'])->name('contacts');
Route::post('/contact_form_process', [App\Http\Controllers\IndexController::class, 'contactForm'])->name('contact_form_process');

//мидлвар для авторзованных
Route::middleware("auth")->group(function () {
	Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
	Route::post('/posts/comment/{id}', [App\Http\Controllers\PostController::class, 'comment'])->name('comment');
});

//мидлвар для неавторизованных
Route::middleware("guest")->group(function () {
	Route::get('/login', [App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
	Route::post('/login_process', [App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

	Route::get('/register', [App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
	Route::post('/register_process', [App\Http\Controllers\AuthController::class, 'register'])->name('register_process');
	
	Route::get('/forgot', [App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
	Route::post('/forgot_process', [App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

laravel/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	use HasFactory;

	protected $fillable = [
		'title',
		'preview',
		'description',
		'thumbnail',
	];

	public function comments()
	{
		return $this->hasMany(Comment::class)->orderBy("created_at"); //связь с таблицей "Comment" по полю "created_at"
	}
}

laravel/app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\PostFormRequest;

use Illuminate\Support\Facades\Gate;
use App\DTO\PostForm;


class PostController extends Controller
{
	
	public function __construct()
	{
	  $this->authorizeResource(Post::class, 'post');
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$posts = Post::orderBy("created_at", "DESC")->paginate(10);
      return view('admin.posts.index', [
			'posts' => $posts,
		]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		return view('admin.posts.create', []);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  PostFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostFormRequest $request)
    {
		$data = $request->validated();
		if ($request->has('thumbnail')) {
			$thumbnail = str_replace("public/posts", "", $request->file('thumbnail')->store("public/posts"));
			$data['thumbnail'] = $thumbnail;
		}
		
      $post = Post::create($data);
		return redirect(route('admin.posts.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
		//$post = Post::findOrFail($id);
		//аналог gate, но для контроллера, а не для шаблона
		$this->authorize('update', $post);

		return view('admin.posts.create', [
			"post" => $post   
		]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  PostFormRequest  $request
     * @param  Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostFormRequest $request, Post $post)
    {
		//$post = Post::findOrFail($id);

		$data = $request->validated();
		if ($request->has('thumbnail')) {
			$thumbnail = str_replace("public/posts", "", $request->file('thumbnail')->store("public/posts"));
			$data['thumbnail'] = $thumbnail;
		}

		$post->update($data);
		return redirect(route('admin.posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
      //  Post::destroy($id);
		$post->delete();
		  return redirect(route("admin.posts.index"));
    }
}

laravel/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentForm;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
	public function index()
	{
		$posts = Post::orderBy("created_at", "DESC")->paginate(3);

		return view('posts.index', [
			'posts' => $posts,
		]);
	}

	//public function show($id)
	//{
	//	$post = Post::findOrFail($id);

	//	return view('posts.show', [
	//		'post' => $post,
	//	]);
	//}
    
	public function show($id)
	{
		 $post = Post::findOrFail($id);
		// $post = Post::with("comments.user")->findOrFail($id);

		 return view('posts.show', [
			"post" => $post,
		 ]);
	}

	public function comment($id, CommentForm $request)
	{
		$post = Post::findOrFail($id);
		$comment = $post->comments()->create($request->validated());
		//вызов события по отправки комментария
		//event(new CommentCreated($comment));

		return redirect(route("posts.show", $id));
	}
}

laravel/resources/views/admin/posts/create.blade.php
@extends('layout.admin')

@section('title', isset($post) ? 'Редактирование статьи' : 'Добавление статьи')

@section('content')	 
	<div class="container mx-auto px-6 py-8">
		<h3 class="text-gray-700 text-3xl font-medium">{{ isset($post) ? "Редактирование статьи: $post->title" : "Добавление статьи" }}</h3>

		<div class="mt-8">

		</div>

		<div class="mt-8">
			<form enctype="multipart/form-data" class="space-y-5 mt-5" method="POST" action="{{ isset($post) ? route('admin.posts.update', $post->id) : route('admin.posts.store') }}">
				@csrf
				@if (isset($post))
					 @method('PUT')
				@endif

				<input name="title" type="text" class="w-full h-12 border border-gray-800 @error('title') border-red-500 @enderror rounded px-3" placeholder="Название" value="{{ $post->title ?? '' }}" />
					@error('title')
						<p class="test-red-500">{{ $message }}</p>
					@enderror

				<input name="preview" type="text" class="w-full h-12 border border-gray-800 @error('preview') border-red-500 @enderror rounded px-3" placeholder="Краткое описание" value="{{ $post->preview ?? '' }}" />
					@error('preview')
						<p class="test-red-500">{{ $message }}</p>
					@enderror	
	
					<input name="description" type="text" class="w-full h-12 border border-gray-800 @error('description') border-red-500 @enderror rounded px-3" placeholder="Описание" value="{{ $post->description ?? '' }}" />
					@error('description')
						<p class="test-red-500">{{ $message }}</p>
					@enderror	

				@if (isset($post) && $post->thumbnail)
					<div>
							<img class="h-64 w-64" src="/storage/posts/{{ $post->thumbnail }}">
					</div>
				@endif
				<input name="thumbnail" type="file" class="w-full h-12" @error('thumbnail') border-red-500 @enderror placeholder="Обложка" />
					@error('thumbnail')
						<p class="test-red-500">{{ $message }}</p>
					@enderror

				<button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium">Сохранить</button>
			</form>
		</div>
	</div>
@endsection

laravel/resources/views/admin/posts/index.blade.php
@extends('layout.admin')

@section('title', 'Статьи')

@section('content')	 
<div class="container mx-auto px-6 py-8">
	<h3 class="text-gray-700 text-3xl font-medium">Статьи</h3>

	<div class="mt-8">
		<a href="{{ route('admin.posts.create') }}" class="text-indigo-600 hover:text-indigo-900">Добавить</a>
	</div>

	<div class="flex flex-col mt-8">
		 <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
			  <div
						 class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
					<table class="min-w-full">
						 <thead>
						 <tr>
							  <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
									Заголовок</th>
							  <th class="px-6 py-3 border-b border-gray-200 bg-gray-50"></th>
						 </tr>
						 </thead>

						 <tbody class="bg-white">
								{{-- статьи --}}
								@foreach ($posts as $post)
									<tr>
										<td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
											<div class="text-sm leading-5 text-gray-900">{{ $post->title }}</div>
										</td>

										<td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium">
											<a href="{{ route('admin.posts.edit', $post->id) }}" class="text-indigo-600 hover:text-indigo-900">Редактировать</a>
											<form action="{{ route('admin.posts.destroy', $post->id) }}" method="POST">
												@csrf
												@method('DELETE')
												<button type="submit" class="text-red-600 hover:text-red-900">Удалить</button>		
											</form>
										</td>
									</tr>
								@endforeach							
						 </tbody>
					</table>
					{{-- пагинация --}}
					{{ $posts->links() }}
			  </div>
		 </div>
	</div>
</div>
@endsection